# Builder
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Copy all source code
COPY . .
COPY infra/wait-for-it.sh /wait-for-it.sh

# Build the binary
RUN chmod +x /wait-for-it.sh
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/api-server/main.go

# Use a minimal image for the final build (5 MB)
FROM alpine:latest

# Copy "app" binary built in builder
WORKDIR /app
COPY --from=builder /app/app .
COPY --from=builder /wait-for-it.sh /wait-for-it.sh

RUN apk add --no-cache bash

EXPOSE 50051

ENTRYPOINT ["/wait-for-it.sh", "rabbitmq:5672", "--", "/wait-for-it.sh", "mongodb:27017", "--", "/app/app"]