services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.21
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: