FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Set the command to run all tests with the integration tag and any other test
CMD ["go", "test", "-v", "./..."]