FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY infra/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
RUN apk add --no-cache bash


ENTRYPOINT ["/wait-for-it.sh", "mongodb:27017", "--", "/wait-for-it.sh", "rabbitmq:5672", "--", "go", "test", "-v", "-tags=integration", "./..."]