services:
  mongodb:
    image: mongo:6.0.21
    restart: always
    ports:
      - "27017:27017"
    tmpfs:
      - /data/db

  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - GRPC_PORT=50051
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=testdb
    depends_on:
      - mongodb

volumes:
  mongo-data: