# Builder
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Copy all source code
COPY . .

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/api-server/main.go

# Use a minimal image for the final build (5 MB)
FROM alpine:latest

# Copy "app" binary built in builder
WORKDIR /app
COPY --from=builder /app/app .

EXPOSE 50051

ENTRYPOINT ["/app/app"]