services:
  mongodb:
    image: mongo:6.0.21
    restart: always
    ports:
      - "27017:27017"
    tmpfs:
      - /data/db

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"

  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - GRPC_PORT=50051
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=testdb
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongo-data: